# Python Assignment
Topic: 3D Arrays and Dictionaries


# Part A – 3D Arrays  

# Question 1  
## Create the following 3D array.

Layer 1

[1, 2, 3]
[4, 5, 6]

Layer 2

[7, 8, 9]
[10, 11, 12]

In [ ]:
Write a Python program to:

Print the complete 3D array.
Print the first layer.
Print the second row of the second layer.
Print the element 11.

In [1]:
import numpy as np

# Create the 3D array
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

# Print the complete 3D array
print("Complete 3D Array:")
print(arr)

# Print the first layer
print("\nFirst Layer:")
print(arr[0])

# Print the second row of the second layer
print("\nSecond row of the second layer:")
print(arr[1, 1])

# Print element 11
print("\nElement 11:")
print(arr[1, 1, 1])

Complete 3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

First Layer:
[[1 2 3]
 [4 5 6]]

Second row of the second layer:
[10 11 12]

Element 11:
11


# Question 2  

Using the same 3D array, reverse the order of layers.

Expected Output

Layer 2

[7, 8, 9]
[10,11,12]

Layer 1

[1,2,3]
[4,5,6]

In [2]:
import numpy as np

# Create the 3D array
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

# Reverse the order of layers
reversed_arr = arr[::-1]

# Print the reversed array
print("Layer 2")
print(reversed_arr[0])

print("\nLayer 1")
print(reversed_arr[1])

Layer 2
[[ 7  8  9]
 [10 11 12]]

Layer 1
[[1 2 3]
 [4 5 6]]


# Question 3  

##  Reverse every row inside every layer.

Expected Output

In [3]:
import numpy as np

# Create the 3D array
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

# Reverse every row inside every layer
reversed_rows = arr[:, :, ::-1]

print(reversed_rows)

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]


# Question 4  

Completely reverse the entire 3D array by reversing:

    the order of layers,
    the order of rows inside each layer,
    the elements inside every row.

Expected Output

[12,11,10]
[9,8,7]
[6,5,4]
[3,2,1]

In [4]:
import numpy as np

# Create the 3D array
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

# Completely reverse the 3D array
reversed_arr = arr[::-1, ::-1, ::-1]

print(reversed_arr)

[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


# Part B – Dictionaries

In [ ]:
# Create a dictionary to store the following student details.

| Key        | Value   |
| ---------- | ------- |
| Roll No    | 101     |
| Name       | Alice   |
| Age        | 20      |
| Department | AI & DS |
| CGPA       | 8.9     |

Display all the information. (use print)

In [ ]:
# Question 6  

Using the dictionary created above,

    Update the CGPA to 9.2
    Add a new key named City with value Chennai
    Display the updated dictionary.

In [ ]:
# Question 7  

Write a program to print

    all keys
    all values
    all key-value pairs

using appropriate dictionary methods.

In [ ]:
# Question 8  

Create the following nested dictionary.

students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

Write a program to

    Print the name of Student2.
    Print the age of Student3.
    Display all student names using a loop.

In [ ]:
# Question 9  

Create a dictionary of five products.

Example

    Laptop
    Mouse
    Keyboard
    Monitor
    Printer

Each product should contain

    Product Name
    Price
    Quantity

Write a program to

    Display all products.
    Print the product with the highest price.
    Calculate the total inventory value

(Formula:  Inventory Value = Price × Quantity)

In [ ]:
# Question 10

Create a dictionary of five students and their marks.

Example

    Alice : 85
    Bob : 92
    Charlie : 78
    David : 88
    Emma : 95

Write a Python program to

    Find the student with the highest marks.
    Find the student with the lowest marks.
    Calculate the average marks.
    Display students who scored more than 85.

In [7]:
# Student dictionary
student = {
    "Roll No": 101,
    "Name": "Alice",
    "Age": 20,
    "Department": "AI & DS",
    "CGPA": 9.2,
    "City": "Chennai"
}

# Print all keys
print("All Keys:")
print(student.keys())

# Print all values
print("\nAll Values:")
print(student.values())

# Print all key-value pairs
print("\nAll Key-Value Pairs:")
print(student.items())

All Keys:
dict_keys(['Roll No', 'Name', 'Age', 'Department', 'CGPA', 'City'])

All Values:
dict_values([101, 'Alice', 20, 'AI & DS', 9.2, 'Chennai'])

All Key-Value Pairs:
dict_items([('Roll No', 101), ('Name', 'Alice'), ('Age', 20), ('Department', 'AI & DS'), ('CGPA', 9.2), ('City', 'Chennai')])


In [6]:
# Create a nested dictionary
students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

# Print the name of Student2
print("Student2 Name:", students["Student2"]["Name"])

# Print the age of Student3
print("Student3 Age:", students["Student3"]["Age"])

# Display all student names using a loop
print("All Student Names:")

for student in students:
    print(students[student]["Name"])

Student2 Name: Alice
Student3 Age: 20
All Student Names:
John
Alice
David


In [8]:
# Create a dictionary of five products
products = {
    "Laptop": {
        "Product Name": "Laptop",
        "Price": 50000,
        "Quantity": 5
    },
    "Mouse": {
        "Product Name": "Mouse",
        "Price": 800,
        "Quantity": 10
    },
    "Keyboard": {
        "Product Name": "Keyboard",
        "Price": 1500,
        "Quantity": 8
    },
    "Monitor": {
        "Product Name": "Monitor",
        "Price": 12000,
        "Quantity": 4
    },
    "Printer": {
        "Product Name": "Printer",
        "Price": 15000,
        "Quantity": 3
    }
}

# Display all products
print("All Products:")

for product in products:
    print(products[product])

# Find the product with the highest price
highest_product = max(products, key=lambda x: products[x]["Price"])

print("\nProduct with Highest Price:")
print(products[highest_product])

# Calculate total inventory value
total_value = 0

for product in products:
    price = products[product]["Price"]
    quantity = products[product]["Quantity"]
    total_value = total_value + (price * quantity)

print("\nTotal Inventory Value:", total_value)

All Products:
{'Product Name': 'Laptop', 'Price': 50000, 'Quantity': 5}
{'Product Name': 'Mouse', 'Price': 800, 'Quantity': 10}
{'Product Name': 'Keyboard', 'Price': 1500, 'Quantity': 8}
{'Product Name': 'Monitor', 'Price': 12000, 'Quantity': 4}
{'Product Name': 'Printer', 'Price': 15000, 'Quantity': 3}

Product with Highest Price:
{'Product Name': 'Laptop', 'Price': 50000, 'Quantity': 5}

Total Inventory Value: 363000


In [9]:
# Create a dictionary of students and their marks
students = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 88,
    "Emma": 95
}

# Find the student with the highest marks
highest_student = max(students, key=students.get)
print("Highest Marks:", highest_student, "-", students[highest_student])

# Find the student with the lowest marks
lowest_student = min(students, key=students.get)
print("Lowest Marks:", lowest_student, "-", students[lowest_student])

# Calculate the average marks
average = sum(students.values()) / len(students)
print("Average Marks:", average)

# Display students who scored more than 85
print("Students who scored more than 85:")

for student, marks in students.items():
    if marks > 85:
        print(student, "-", marks)

Highest Marks: Emma - 95
Lowest Marks: Charlie - 78
Average Marks: 87.6
Students who scored more than 85:
Bob - 92
David - 88
Emma - 95


In [10]:
# Create a dictionary of students and their marks
students = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 88,
    "Emma": 95
}

# Find the student with the highest marks
highest_student = max(students, key=students.get)
print("Highest Marks:", highest_student, "-", students[highest_student])

# Find the student with the lowest marks
lowest_student = min(students, key=students.get)
print("Lowest Marks:", lowest_student, "-", students[lowest_student])

# Calculate the average marks
average = sum(students.values()) / len(students)
print("Average Marks:", average)

# Display students who scored more than 85
print("Students who scored more than 85:")

for student, marks in students.items():
    if marks > 85:
        print(student, "-", marks)

Highest Marks: Emma - 95
Lowest Marks: Charlie - 78
Average Marks: 87.6
Students who scored more than 85:
Bob - 92
David - 88
Emma - 95
